-- ============================================================
-- Session 16 -- multilingual retrieval keywords for RED/ORANGE scenarios
--
-- Dovtedy malo vsetkych 84 V2 scenarov keywords LEN po anglicky.
-- Rezident, ktory napise otazku po spanielsky/francuzsky/nemecky
-- bez akychkolvek anglickych slov, tak nemusel trafit spravny
-- scenar (padol do fallbacku). Tato migracia doplna ES/FR/DE
-- keywords pre vsetkych 54 RED/ORANGE (najkritickejsich) scenarov.
--
-- Idempotentne: kazdy UPDATE pridava nove keywords iba ak tam
-- este nie su (marker = prva pridavana ES fraza).
-- ============================================================

update ai_knowledge_base set keywords = keywords || '{"fuga de agua arriba","gotea el techo","vecino de arriba inunda","agua desde arriba","fuite d''eau au-dessus","plafond qui coule","voisin du dessus inonde","eau venant d''en haut","wasser von oben","decke tropft","nachbar oben überflutet","wasser sickert durch"}' where intent_code = 'WAT-01' and not ('fuga de agua arriba' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"tubería rota","fuga en mi apartamento","fuga de agua interna","grifo tubería gotea","tuyau cassé","fuite dans mon appartement","fuite d''eau interne","fuite robinet tuyau","rohr geplatzt","leck in meiner wohnung","wasserleck innen","wasserhahn rohr undicht"}' where intent_code = 'WAT-02' and not ('tubería rota' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"gotea al piso de abajo","inundo al vecino de abajo","mi fuga afecta al vecino","fuite vers le bas","j''inonde le voisin du dessous","ma fuite affecte le voisin","leck nach unten","überflute nachbarn unten","mein leck betrifft nachbarn"}' where intent_code = 'WAT-03' and not ('gotea al piso de abajo' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"fuga tubería comunitaria","agua en el pasillo","inundación zona común","tubería rota edificio","fuite tuyau communautaire","eau dans le couloir","inondation zone commune","tuyau cassé immeuble","leck gemeinschaftsrohr","wasser im flur","überflutung gemeinschaftsbereich","rohrbruch gebäude"}' where intent_code = 'WAT-04' and not ('fuga tubería comunitaria' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"aguas residuales atascadas","inodoro desbordado","aguas negras","atasco de desagüe","eaux usées refoulent","toilettes débordent","eaux noires","refoulement égout","abwasser rückstau","toilette überläuft","abwasser rückschlag","kanalisation verstopft"}' where intent_code = 'WAT-05' and not ('aguas residuales atascadas' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"gotea la lluvia","fuga en el techo","fuga en la terraza","agua por la ventana","entrada de tormenta","fuite pluie","fuite toit","fuite terrasse","eau par la fenêtre","infiltration tempête","regen dringt ein","dachleck","terrassenleck","wasser durchs fenster","sturmwasser eindringen"}' where intent_code = 'WAT-07' and not ('gotea la lluvia' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"garaje inundado","agua en el sótano","parking subterráneo inundado","garage inondé","eau au sous-sol","parking souterrain inondé","garage überflutet","wasser im keller","tiefgarage überflutet"}' where intent_code = 'WAT-08' and not ('garaje inundado' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"corte de luz edificio","apagón comunidad","fallo eléctrico general","coupure de courant immeuble","panne communauté","panne électrique générale","stromausfall gebäude","stromausfall gemeinschaft","allgemeiner stromausfall"}' where intent_code = 'ELE-02' and not ('corte de luz edificio' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"olor a quemado eléctrico","chispas","enchufe caliente","humo del electrodoméstico","odeur de brûlé électrique","étincelles","prise chaude","fumée appareil","elektrischer brandgeruch","funken","heiße steckdose","rauch gerät"}' where intent_code = 'ELE-04' and not ('olor a quemado eléctrico' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"agua por la luz","enchufe mojado","gotea electricidad techo","agua y electricidad","eau par la lumière","prise mouillée","fuite plafond électricité","eau et électricité","wasser durch die lampe","nasse steckdose","deckenleck strom","wasser und strom"}' where intent_code = 'ELE-05' and not ('agua por la luz' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"cable expuesto","cable dañado","cable vivo zona común","câble exposé","câble endommagé","câble sous tension zone commune","freiliegendes kabel","beschädigtes kabel","stromführendes kabel gemeinschaftsbereich"}' where intent_code = 'ELE-06' and not ('cable expuesto' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"incendio en mi apartamento","fuego en la cocina","incendio en mi piso","incendie dans mon appartement","feu dans la cuisine","incendie chez moi","feuer in meiner wohnung","küchenbrand","brand in meiner wohnung"}' where intent_code = 'FIR-01' and not ('incendio en mi apartamento' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"humo del vecino","incendio al lado","humo desde el apartamento","fumée chez le voisin","incendie à côté","fumée depuis l''appartement","rauch beim nachbarn","feuer nebenan","rauch aus der wohnung"}' where intent_code = 'FIR-02' and not ('humo del vecino' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"incendio en el garaje","coche en llamas","incendio de vehículo","incendie au garage","voiture en feu","incendie de véhicule","feuer in der garage","auto brennt","fahrzeugbrand"}' where intent_code = 'FIR-03' and not ('incendio en el garaje' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"batería humeando","cargador sobrecalentado","bicicleta eléctrica batería","coche eléctrico humo","batterie qui fume","chargeur surchauffe","vélo électrique batterie","voiture électrique fumée","batterie raucht","ladegerät überhitzt","e-bike batterie","elektroauto rauch"}' where intent_code = 'FIR-04' and not ('batería humeando' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"olor a gas","fuga de gas","huele a gas","odeur de gaz","fuite de gaz","ça sent le gaz","gasgeruch","gasleck","riecht nach gas"}' where intent_code = 'FIR-05' and not ('olor a gas' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"monóxido de carbono","alarma de CO","mareo varias personas","monoxyde de carbone","alarme CO","plusieurs personnes étourdies","kohlenmonoxid","CO alarm","mehrere personen schwindelig"}' where intent_code = 'FIR-06' and not ('monóxido de carbono' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"emergencia médica","ambulancia","enfermedad grave","herida","urgence médicale","ambulance","maladie grave","blessure","medizinischer notfall","krankenwagen","schwere krankheit","verletzung"}' where intent_code = 'MED-01' and not ('emergencia médica' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"inconsciente","colapsó","no responde","inconscient","s''est effondré","ne répond pas","bewusstlos","zusammengebrochen","reagiert nicht"}' where intent_code = 'MED-02' and not ('inconsciente' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"caída","resbaló","lesión zona común","accidente tropiezo","chute","a glissé","blessure zone commune","accident trébuchement","sturz","ausgerutscht","verletzung gemeinschaftsbereich","stolperunfall"}' where intent_code = 'MED-03' and not ('caída' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"ahogamiento","emergencia en la piscina","bajo el agua","casi se ahoga","noyade","urgence piscine","sous l''eau","a failli se noyer","ertrinken","notfall im pool","unter wasser","beinahe ertrunken"}' where intent_code = 'MED-04' and not ('ahogamiento' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"niño perdido","persona desaparecida","residente vulnerable perdido","enfant perdu","personne disparue","résident vulnérable disparu","kind vermisst","vermisste person","schutzbedürftiger bewohner vermisst"}' where intent_code = 'MED-05' and not ('niño perdido' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"intoxicación","exposición química","tragó limpiador","humos tóxicos","empoisonnement","exposition chimique","a avalé du détergent","fumées toxiques","vergiftung","chemische exposition","reiniger verschluckt","giftige dämpfe"}' where intent_code = 'MED-06' and not ('intoxicación' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"robo en curso","intruso","allanamiento en progreso","cambriolage en cours","intrus","effraction en cours","einbruch im gange","eindringling","einbruch läuft gerade"}' where intent_code = 'SEC-01' and not ('robo en curso' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"robo descubierto","puerta forzada","casa robada","cambriolage découvert","porte forcée","maison cambriolée","einbruch entdeckt","tür aufgebrochen","wohnung ausgeraubt"}' where intent_code = 'SEC-02' and not ('robo descubierto' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"persona sospechosa","desconocido","preocupación de seguridad","personne suspecte","inconnu","préoccupation sécurité","verdächtige person","unbekannter","sicherheitsbedenken"}' where intent_code = 'SEC-03' and not ('persona sospechosa' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"persona agresiva","amenaza","violencia","vecino amenazante","personne agressive","menace","violence","voisin menaçant","aggressive person","drohung","gewalt","bedrohlicher nachbar"}' where intent_code = 'SEC-04' and not ('persona agresiva' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"robo en el garaje","robo en el trastero","bicicleta robada","vol au garage","vol au débarras","vélo volé","diebstahl in der garage","diebstahl im lager","fahrrad gestohlen"}' where intent_code = 'SEC-06' and not ('robo en el garaje' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"puerta de seguridad abierta","verja sin cerrar","entrada no cierra","porte de sécurité ouverte","portail non fermé","entrée ne ferme pas","sicherheitstür offen","tor nicht verschlossen","eingang schließt nicht"}' where intent_code = 'SEC-08' and not ('puerta de seguridad abierta' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"atrapado en el ascensor","ascensor atascado","persona atrapada elevador","coincé dans l''ascenseur","ascenseur bloqué","personne coincée ascenseur","im aufzug stecken geblieben","aufzug blockiert","person im aufzug eingeschlossen"}' where intent_code = 'BLD-01' and not ('atrapado en el ascensor' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"puerta del garaje atascada","verja de vehículos rota","puerta garaje","porte de garage bloquée","portail véhicule cassé","porte garage","garagentor klemmt","fahrzeugtor kaputt","garagentür"}' where intent_code = 'BLD-03' and not ('puerta del garaje atascada' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"emergencia apartamento vacío","propietario no está","no puedo contactar al vecino","urgence appartement vide","propriétaire absent","impossible de contacter le voisin","notfall leere wohnung","eigentümer nicht da","nachbar nicht erreichbar"}' where intent_code = 'BLD-08' and not ('emergencia apartamento vacío' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"grieta estructural","techo hundido","daño estructural","techo combado","fissure structurelle","plafond affaissé","dommage structurel","plafond qui s''affaisse","strukturriss","decke sackt durch","strukturschaden","durchhängende decke"}' where intent_code = 'BLD-09' and not ('grieta estructural' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"barandilla rota","fachada cayendo","cristal comunitario roto","riesgo de caída","garde-corps cassé","façade qui tombe","verre communautaire cassé","risque de chute","geländer kaputt","fassade fällt","gemeinschaftsglas zerbrochen","sturzgefahr"}' where intent_code = 'BLD-10' and not ('barandilla rota' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"lluvia torrencial","inundación repentina","alerta meteorológica roja","inundación tormenta","pluie torrentielle","inondation soudaine","alerte météo rouge","inondation tempête","sintflutartiger regen","sturzflut","rote wetterwarnung","sturmflut"}' where intent_code = 'WEA-01' and not ('lluvia torrencial' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"viento fuerte","tormenta","objetos volando","alerta de viento fuerte","vent fort","tempête","objets qui volent","alerte vent fort","starker wind","sturm","fliegende gegenstände","sturmwarnung"}' where intent_code = 'WEA-02' and not ('viento fuerte' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"incendio forestal","fuego en el monte","humo fuera","alerta de evacuación fuego","feu de forêt","incendie dans la colline","fumée extérieure","alerte évacuation incendie","waldbrand","feuer im wald","rauch draußen","evakuierungswarnung feuer"}' where intent_code = 'WEA-03' and not ('incendio forestal' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"terremoto","temblor","el edificio tiembla","tremblement de terre","séisme","le bâtiment tremble","erdbeben","beben","das gebäude wackelt"}' where intent_code = 'WEA-04' and not ('terremoto' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"maremoto","alerta costera","evacuación costa","raz de marée","alerte côtière","évacuation côte","tsunami warnung","küstenevakuierung","warnung küste"}' where intent_code = 'WEA-05' and not ('maremoto' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"ola de calor","agotamiento por calor","golpe de calor","calor extremo","canicule","épuisement par la chaleur","coup de chaleur","chaleur extrême","hitzewelle","hitzeerschöpfung","hitzschlag","extreme hitze"}' where intent_code = 'WEA-06' and not ('ola de calor' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"piscina sucia","olor químico piscina","piscina verde","agua de piscina insegura","piscine sale","odeur chimique piscine","piscine verte","eau de piscine dangereuse","pool schmutzig","chemischer geruch pool","grüner pool","unsicheres poolwasser"}' where intent_code = 'COM-01' and not ('piscina sucia' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"cristal en la piscina","objeto afilado piscina","botella rota piscina","verre dans la piscine","objet tranchant piscine","bouteille cassée piscine","glas im pool","scharfer gegenstand pool","kaputte flasche pool"}' where intent_code = 'COM-02' and not ('cristal en la piscina' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"suelo resbaladizo","derrame","riesgo de tropiezo","suelo mojado","sol glissant","déversement","risque de trébuchement","sol mouillé","rutschiger boden","verschüttet","stolpergefahr","nasser boden"}' where intent_code = 'COM-03' and not ('suelo resbaladizo' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"árbol caído","rama caída","árbol peligroso","arbre tombé","branche tombée","arbre dangereux","umgestürzter baum","herabgefallener ast","gefährlicher baum"}' where intent_code = 'COM-04' and not ('árbol caído' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"garaje bloqueado","coche bloqueando acceso","ruta de emergencia bloqueada","garage bloqué","voiture bloquant l''accès","route d''urgence bloquée","garage blockiert","auto blockiert zufahrt","notfallzufahrt blockiert"}' where intent_code = 'PAR-02' and not ('garaje bloqueado' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"coche abandonado","vehículo con fuga","coche sospechoso","voiture abandonnée","véhicule qui fuit","voiture suspecte","verlassenes auto","auslaufendes fahrzeug","verdächtiges auto"}' where intent_code = 'PAR-04' and not ('coche abandonado' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"alarma sonando","sirena","pitido de alarma","alarma desconocida","alarme qui sonne","sirène","bip alarme","alarme inconnue","alarm ertönt","sirene","alarm piept","unbekannter alarm"}' where intent_code = 'SAF-01' and not ('alarma sonando' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"atrapado en el garaje","atrapado en sala","encerrado en la verja","coincé au garage","coincé dans la salle","enfermé au portail","im garage eingeschlossen","im raum eingesperrt","am tor eingeschlossen"}' where intent_code = 'SAF-02' and not ('atrapado en el garaje' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"perro agresivo","perro suelto","animal peligroso","chien agressif","chien en liberté","animal dangereux","aggressiver hund","freilaufender hund","gefährliches tier"}' where intent_code = 'SAF-03' and not ('perro agresivo' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"serpiente","animal salvaje","fauna peligrosa","serpent","animal sauvage","faune dangereuse","schlange","wildtier","gefährliche tierwelt"}' where intent_code = 'SAF-04' and not ('serpiente' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"olor químico","humos","olor fuerte desconocido","odeur chimique","fumées","forte odeur inconnue","chemischer geruch","dämpfe","starker unbekannter geruch"}' where intent_code = 'SAF-05' and not ('olor químico' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"evacuación","salir del edificio","evacuación de emergencia","évacuation","quitter le bâtiment","évacuation d''urgence","evakuierung","gebäude verlassen","notfallevakuierung"}' where intent_code = 'SAF-06' and not ('evacuación' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"mantenimiento no responde","seguridad no responde","no puedo contactar emergencia","maintenance ne répond pas","sécurité ne répond pas","impossible de contacter urgence","wartung antwortet nicht","sicherheit antwortet nicht","notfallkontakt nicht erreichbar"}' where intent_code = 'SAF-07' and not ('mantenimiento no responde' = any(keywords));
update ai_knowledge_base set keywords = keywords || '{"es esto una emergencia","no sé qué hacer","debo llamar al 112","est-ce une urgence","je ne sais pas quoi faire","dois-je appeler le 112","ist das ein notfall","weiß nicht was tun","soll ich 112 anrufen"}' where intent_code = 'SAF-08' and not ('es esto una emergencia' = any(keywords));
